artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/rahul6796/datasets1/raw/main/squad.zip
  local_file_dir: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_FILES: ['train', 'validation']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/squad
  tokenizer_name: distilbert/distilbert-base-cased-distilled-squad

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/squad_new
  model_ckpt: distilbert/distilbert-base-cased-distilled-squad




